from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

AG_AVG: AggregateEnum
AG_COUNT: AggregateEnum
AG_DCOUNT: AggregateEnum
AG_DISTINCT: AggregateEnum
AG_INSTANCE_ATTRIBUTE: AggregateEnum
AG_MAX: AggregateEnum
AG_MIN: AggregateEnum
AG_NONE: AggregateEnum
AG_STDDEV: AggregateEnum
AG_SUM: AggregateEnum
AG_VALUES_POINT: AggregateEnum
DESCRIPTOR: _descriptor.FileDescriptor
DS_BOOLEAN: DataTypeEnum
DS_BYTE: DataTypeEnum
DS_BYTESTR: DataTypeEnum
DS_COMPLEX: DataTypeEnum
DS_DATE: DataTypeEnum
DS_DCOMPLEX: DataTypeEnum
DS_DOUBLE: DataTypeEnum
DS_ENUM: DataTypeEnum
DS_EXTERNALREFERENCE: DataTypeEnum
DS_FLOAT: DataTypeEnum
DS_LONG: DataTypeEnum
DS_LONGLONG: DataTypeEnum
DS_SHORT: DataTypeEnum
DS_STRING: DataTypeEnum
DT_BLOB: DataTypeEnum
DT_BOOLEAN: DataTypeEnum
DT_BYTE: DataTypeEnum
DT_BYTESTR: DataTypeEnum
DT_COMPLEX: DataTypeEnum
DT_DATE: DataTypeEnum
DT_DCOMPLEX: DataTypeEnum
DT_DOUBLE: DataTypeEnum
DT_ENUM: DataTypeEnum
DT_EXTERNALREFERENCE: DataTypeEnum
DT_FLOAT: DataTypeEnum
DT_LONG: DataTypeEnum
DT_LONGLONG: DataTypeEnum
DT_SHORT: DataTypeEnum
DT_STRING: DataTypeEnum
DT_UNKNOWN: DataTypeEnum

class AsamPath(_message.Message):
    __slots__ = ["path"]
    PATH_FIELD_NUMBER: _ClassVar[int]
    path: str
    def __init__(self, path: _Optional[str] = ...) -> None: ...

class BaseModel(_message.Message):
    __slots__ = ["entities", "enumerations", "version"]
    class DerivationEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = []
    class Attribute(_message.Message):
        __slots__ = ["autogenerated", "data_type", "enumeration", "mandatory", "name", "obligatory"]
        AUTOGENERATED_FIELD_NUMBER: _ClassVar[int]
        DATA_TYPE_FIELD_NUMBER: _ClassVar[int]
        ENUMERATION_FIELD_NUMBER: _ClassVar[int]
        MANDATORY_FIELD_NUMBER: _ClassVar[int]
        NAME_FIELD_NUMBER: _ClassVar[int]
        OBLIGATORY_FIELD_NUMBER: _ClassVar[int]
        autogenerated: bool
        data_type: DataTypeEnum
        enumeration: str
        mandatory: bool
        name: str
        obligatory: bool
        def __init__(self, name: _Optional[str] = ..., data_type: _Optional[_Union[DataTypeEnum, str]] = ..., mandatory: bool = ..., obligatory: bool = ..., autogenerated: bool = ..., enumeration: _Optional[str] = ...) -> None: ...
    class EntitiesEntry(_message.Message):
        __slots__ = ["key", "value"]
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: BaseModel.Entity
        def __init__(self, key: _Optional[str] = ..., value: _Optional[_Union[BaseModel.Entity, _Mapping]] = ...) -> None: ...
    class Entity(_message.Message):
        __slots__ = ["attributes", "bid", "derivation", "name", "relations"]
        class AttributesEntry(_message.Message):
            __slots__ = ["key", "value"]
            KEY_FIELD_NUMBER: _ClassVar[int]
            VALUE_FIELD_NUMBER: _ClassVar[int]
            key: str
            value: BaseModel.Attribute
            def __init__(self, key: _Optional[str] = ..., value: _Optional[_Union[BaseModel.Attribute, _Mapping]] = ...) -> None: ...
        class RelationsEntry(_message.Message):
            __slots__ = ["key", "value"]
            KEY_FIELD_NUMBER: _ClassVar[int]
            VALUE_FIELD_NUMBER: _ClassVar[int]
            key: str
            value: BaseModel.Relation
            def __init__(self, key: _Optional[str] = ..., value: _Optional[_Union[BaseModel.Relation, _Mapping]] = ...) -> None: ...
        ATTRIBUTES_FIELD_NUMBER: _ClassVar[int]
        BID_FIELD_NUMBER: _ClassVar[int]
        DERIVATION_FIELD_NUMBER: _ClassVar[int]
        NAME_FIELD_NUMBER: _ClassVar[int]
        RELATIONS_FIELD_NUMBER: _ClassVar[int]
        attributes: _containers.MessageMap[str, BaseModel.Attribute]
        bid: int
        derivation: BaseModel.DerivationEnum
        name: str
        relations: _containers.MessageMap[str, BaseModel.Relation]
        def __init__(self, name: _Optional[str] = ..., bid: _Optional[int] = ..., derivation: _Optional[_Union[BaseModel.DerivationEnum, str]] = ..., attributes: _Optional[_Mapping[str, BaseModel.Attribute]] = ..., relations: _Optional[_Mapping[str, BaseModel.Relation]] = ...) -> None: ...
    class EnumerationsEntry(_message.Message):
        __slots__ = ["key", "value"]
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: Model.Enumeration
        def __init__(self, key: _Optional[str] = ..., value: _Optional[_Union[Model.Enumeration, _Mapping]] = ...) -> None: ...
    class Relation(_message.Message):
        __slots__ = ["entity_names", "inverse_name", "inverse_range_max", "inverse_range_min", "mandatory", "name", "range_max", "range_min", "relation_type", "relationship"]
        ENTITY_NAMES_FIELD_NUMBER: _ClassVar[int]
        INVERSE_NAME_FIELD_NUMBER: _ClassVar[int]
        INVERSE_RANGE_MAX_FIELD_NUMBER: _ClassVar[int]
        INVERSE_RANGE_MIN_FIELD_NUMBER: _ClassVar[int]
        MANDATORY_FIELD_NUMBER: _ClassVar[int]
        NAME_FIELD_NUMBER: _ClassVar[int]
        RANGE_MAX_FIELD_NUMBER: _ClassVar[int]
        RANGE_MIN_FIELD_NUMBER: _ClassVar[int]
        RELATIONSHIP_FIELD_NUMBER: _ClassVar[int]
        RELATION_TYPE_FIELD_NUMBER: _ClassVar[int]
        entity_names: _containers.RepeatedScalarFieldContainer[str]
        inverse_name: str
        inverse_range_max: int
        inverse_range_min: int
        mandatory: bool
        name: str
        range_max: int
        range_min: int
        relation_type: Model.RelationTypeEnum
        relationship: Model.RelationshipEnum
        def __init__(self, name: _Optional[str] = ..., inverse_name: _Optional[str] = ..., entity_names: _Optional[_Iterable[str]] = ..., range_min: _Optional[int] = ..., range_max: _Optional[int] = ..., relationship: _Optional[_Union[Model.RelationshipEnum, str]] = ..., inverse_range_min: _Optional[int] = ..., inverse_range_max: _Optional[int] = ..., relation_type: _Optional[_Union[Model.RelationTypeEnum, str]] = ..., mandatory: bool = ...) -> None: ...
    DV_SINGLE: BaseModel.DerivationEnum
    DV_TREE_AT_INSTANCE: BaseModel.DerivationEnum
    DV_TREE_AT_MODEL: BaseModel.DerivationEnum
    DV_UNRESTRICTED: BaseModel.DerivationEnum
    ENTITIES_FIELD_NUMBER: _ClassVar[int]
    ENUMERATIONS_FIELD_NUMBER: _ClassVar[int]
    VERSION_FIELD_NUMBER: _ClassVar[int]
    entities: _containers.MessageMap[str, BaseModel.Entity]
    enumerations: _containers.MessageMap[str, Model.Enumeration]
    version: str
    def __init__(self, version: _Optional[str] = ..., enumerations: _Optional[_Mapping[str, Model.Enumeration]] = ..., entities: _Optional[_Mapping[str, BaseModel.Entity]] = ...) -> None: ...

class BooleanArray(_message.Message):
    __slots__ = ["values"]
    VALUES_FIELD_NUMBER: _ClassVar[int]
    values: _containers.RepeatedScalarFieldContainer[bool]
    def __init__(self, values: _Optional[_Iterable[bool]] = ...) -> None: ...

class ByteArray(_message.Message):
    __slots__ = ["values"]
    VALUES_FIELD_NUMBER: _ClassVar[int]
    values: bytes
    def __init__(self, values: _Optional[bytes] = ...) -> None: ...

class BytestrArray(_message.Message):
    __slots__ = ["values"]
    VALUES_FIELD_NUMBER: _ClassVar[int]
    values: _containers.RepeatedScalarFieldContainer[bytes]
    def __init__(self, values: _Optional[_Iterable[bytes]] = ...) -> None: ...

class ContextVariables(_message.Message):
    __slots__ = ["variables"]
    class ContextVariableValue(_message.Message):
        __slots__ = ["boolean_array", "byte_array", "double_array", "float_array", "long_array", "longlong_array", "string_array"]
        BOOLEAN_ARRAY_FIELD_NUMBER: _ClassVar[int]
        BYTE_ARRAY_FIELD_NUMBER: _ClassVar[int]
        DOUBLE_ARRAY_FIELD_NUMBER: _ClassVar[int]
        FLOAT_ARRAY_FIELD_NUMBER: _ClassVar[int]
        LONGLONG_ARRAY_FIELD_NUMBER: _ClassVar[int]
        LONG_ARRAY_FIELD_NUMBER: _ClassVar[int]
        STRING_ARRAY_FIELD_NUMBER: _ClassVar[int]
        boolean_array: BooleanArray
        byte_array: ByteArray
        double_array: DoubleArray
        float_array: FloatArray
        long_array: LongArray
        longlong_array: LonglongArray
        string_array: StringArray
        def __init__(self, string_array: _Optional[_Union[StringArray, _Mapping]] = ..., long_array: _Optional[_Union[LongArray, _Mapping]] = ..., float_array: _Optional[_Union[FloatArray, _Mapping]] = ..., boolean_array: _Optional[_Union[BooleanArray, _Mapping]] = ..., byte_array: _Optional[_Union[ByteArray, _Mapping]] = ..., double_array: _Optional[_Union[DoubleArray, _Mapping]] = ..., longlong_array: _Optional[_Union[LonglongArray, _Mapping]] = ...) -> None: ...
    class VariablesEntry(_message.Message):
        __slots__ = ["key", "value"]
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: ContextVariables.ContextVariableValue
        def __init__(self, key: _Optional[str] = ..., value: _Optional[_Union[ContextVariables.ContextVariableValue, _Mapping]] = ...) -> None: ...
    VARIABLES_FIELD_NUMBER: _ClassVar[int]
    variables: _containers.MessageMap[str, ContextVariables.ContextVariableValue]
    def __init__(self, variables: _Optional[_Mapping[str, ContextVariables.ContextVariableValue]] = ...) -> None: ...

class ContextVariablesFilter(_message.Message):
    __slots__ = ["pattern"]
    PATTERN_FIELD_NUMBER: _ClassVar[int]
    pattern: str
    def __init__(self, pattern: _Optional[str] = ...) -> None: ...

class CopyRequest(_message.Message):
    __slots__ = ["aid", "iid", "mode", "new_name", "new_version"]
    class CopyModeEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = []
    AID_FIELD_NUMBER: _ClassVar[int]
    CM_DEEP: CopyRequest.CopyModeEnum
    CM_SHALLOW: CopyRequest.CopyModeEnum
    IID_FIELD_NUMBER: _ClassVar[int]
    MODE_FIELD_NUMBER: _ClassVar[int]
    NEW_NAME_FIELD_NUMBER: _ClassVar[int]
    NEW_VERSION_FIELD_NUMBER: _ClassVar[int]
    aid: int
    iid: int
    mode: CopyRequest.CopyModeEnum
    new_name: str
    new_version: str
    def __init__(self, mode: _Optional[_Union[CopyRequest.CopyModeEnum, str]] = ..., aid: _Optional[int] = ..., iid: _Optional[int] = ..., new_name: _Optional[str] = ..., new_version: _Optional[str] = ...) -> None: ...

class DataMatrices(_message.Message):
    __slots__ = ["matrices", "partial_result"]
    MATRICES_FIELD_NUMBER: _ClassVar[int]
    PARTIAL_RESULT_FIELD_NUMBER: _ClassVar[int]
    matrices: _containers.RepeatedCompositeFieldContainer[DataMatrix]
    partial_result: bool
    def __init__(self, matrices: _Optional[_Iterable[_Union[DataMatrix, _Mapping]]] = ..., partial_result: bool = ...) -> None: ...

class DataMatrix(_message.Message):
    __slots__ = ["aid", "base_name", "columns", "name", "row_start", "values_remove_length", "values_start", "values_update_mode"]
    class UpdateModeEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = []
    class Column(_message.Message):
        __slots__ = ["aggregate", "base_name", "boolean_array", "boolean_arrays", "byte_array", "byte_arrays", "bytestr_array", "bytestr_arrays", "data_type", "double_array", "double_arrays", "float_array", "float_arrays", "is_null", "long_array", "long_arrays", "longlong_array", "longlong_arrays", "name", "string_array", "string_arrays", "unit_id", "unknown_arrays"]
        class BooleanArrays(_message.Message):
            __slots__ = ["values"]
            VALUES_FIELD_NUMBER: _ClassVar[int]
            values: _containers.RepeatedCompositeFieldContainer[BooleanArray]
            def __init__(self, values: _Optional[_Iterable[_Union[BooleanArray, _Mapping]]] = ...) -> None: ...
        class ByteArrays(_message.Message):
            __slots__ = ["values"]
            VALUES_FIELD_NUMBER: _ClassVar[int]
            values: _containers.RepeatedCompositeFieldContainer[ByteArray]
            def __init__(self, values: _Optional[_Iterable[_Union[ByteArray, _Mapping]]] = ...) -> None: ...
        class BytestrArrays(_message.Message):
            __slots__ = ["values"]
            VALUES_FIELD_NUMBER: _ClassVar[int]
            values: _containers.RepeatedCompositeFieldContainer[BytestrArray]
            def __init__(self, values: _Optional[_Iterable[_Union[BytestrArray, _Mapping]]] = ...) -> None: ...
        class DoubleArrays(_message.Message):
            __slots__ = ["values"]
            VALUES_FIELD_NUMBER: _ClassVar[int]
            values: _containers.RepeatedCompositeFieldContainer[DoubleArray]
            def __init__(self, values: _Optional[_Iterable[_Union[DoubleArray, _Mapping]]] = ...) -> None: ...
        class FloatArrays(_message.Message):
            __slots__ = ["values"]
            VALUES_FIELD_NUMBER: _ClassVar[int]
            values: _containers.RepeatedCompositeFieldContainer[FloatArray]
            def __init__(self, values: _Optional[_Iterable[_Union[FloatArray, _Mapping]]] = ...) -> None: ...
        class LongArrays(_message.Message):
            __slots__ = ["values"]
            VALUES_FIELD_NUMBER: _ClassVar[int]
            values: _containers.RepeatedCompositeFieldContainer[LongArray]
            def __init__(self, values: _Optional[_Iterable[_Union[LongArray, _Mapping]]] = ...) -> None: ...
        class LonglongArrays(_message.Message):
            __slots__ = ["values"]
            VALUES_FIELD_NUMBER: _ClassVar[int]
            values: _containers.RepeatedCompositeFieldContainer[LonglongArray]
            def __init__(self, values: _Optional[_Iterable[_Union[LonglongArray, _Mapping]]] = ...) -> None: ...
        class StringArrays(_message.Message):
            __slots__ = ["values"]
            VALUES_FIELD_NUMBER: _ClassVar[int]
            values: _containers.RepeatedCompositeFieldContainer[StringArray]
            def __init__(self, values: _Optional[_Iterable[_Union[StringArray, _Mapping]]] = ...) -> None: ...
        class UnknownArray(_message.Message):
            __slots__ = ["boolean_array", "byte_array", "bytestr_array", "data_type", "double_array", "float_array", "long_array", "longlong_array", "string_array", "unit_id"]
            BOOLEAN_ARRAY_FIELD_NUMBER: _ClassVar[int]
            BYTESTR_ARRAY_FIELD_NUMBER: _ClassVar[int]
            BYTE_ARRAY_FIELD_NUMBER: _ClassVar[int]
            DATA_TYPE_FIELD_NUMBER: _ClassVar[int]
            DOUBLE_ARRAY_FIELD_NUMBER: _ClassVar[int]
            FLOAT_ARRAY_FIELD_NUMBER: _ClassVar[int]
            LONGLONG_ARRAY_FIELD_NUMBER: _ClassVar[int]
            LONG_ARRAY_FIELD_NUMBER: _ClassVar[int]
            STRING_ARRAY_FIELD_NUMBER: _ClassVar[int]
            UNIT_ID_FIELD_NUMBER: _ClassVar[int]
            boolean_array: BooleanArray
            byte_array: ByteArray
            bytestr_array: BytestrArray
            data_type: DataTypeEnum
            double_array: DoubleArray
            float_array: FloatArray
            long_array: LongArray
            longlong_array: LonglongArray
            string_array: StringArray
            unit_id: int
            def __init__(self, data_type: _Optional[_Union[DataTypeEnum, str]] = ..., unit_id: _Optional[int] = ..., string_array: _Optional[_Union[StringArray, _Mapping]] = ..., long_array: _Optional[_Union[LongArray, _Mapping]] = ..., float_array: _Optional[_Union[FloatArray, _Mapping]] = ..., boolean_array: _Optional[_Union[BooleanArray, _Mapping]] = ..., byte_array: _Optional[_Union[ByteArray, _Mapping]] = ..., double_array: _Optional[_Union[DoubleArray, _Mapping]] = ..., longlong_array: _Optional[_Union[LonglongArray, _Mapping]] = ..., bytestr_array: _Optional[_Union[BytestrArray, _Mapping]] = ...) -> None: ...
        class UnknownArrays(_message.Message):
            __slots__ = ["values"]
            VALUES_FIELD_NUMBER: _ClassVar[int]
            values: _containers.RepeatedCompositeFieldContainer[DataMatrix.Column.UnknownArray]
            def __init__(self, values: _Optional[_Iterable[_Union[DataMatrix.Column.UnknownArray, _Mapping]]] = ...) -> None: ...
        AGGREGATE_FIELD_NUMBER: _ClassVar[int]
        BASE_NAME_FIELD_NUMBER: _ClassVar[int]
        BOOLEAN_ARRAYS_FIELD_NUMBER: _ClassVar[int]
        BOOLEAN_ARRAY_FIELD_NUMBER: _ClassVar[int]
        BYTESTR_ARRAYS_FIELD_NUMBER: _ClassVar[int]
        BYTESTR_ARRAY_FIELD_NUMBER: _ClassVar[int]
        BYTE_ARRAYS_FIELD_NUMBER: _ClassVar[int]
        BYTE_ARRAY_FIELD_NUMBER: _ClassVar[int]
        DATA_TYPE_FIELD_NUMBER: _ClassVar[int]
        DOUBLE_ARRAYS_FIELD_NUMBER: _ClassVar[int]
        DOUBLE_ARRAY_FIELD_NUMBER: _ClassVar[int]
        FLOAT_ARRAYS_FIELD_NUMBER: _ClassVar[int]
        FLOAT_ARRAY_FIELD_NUMBER: _ClassVar[int]
        IS_NULL_FIELD_NUMBER: _ClassVar[int]
        LONGLONG_ARRAYS_FIELD_NUMBER: _ClassVar[int]
        LONGLONG_ARRAY_FIELD_NUMBER: _ClassVar[int]
        LONG_ARRAYS_FIELD_NUMBER: _ClassVar[int]
        LONG_ARRAY_FIELD_NUMBER: _ClassVar[int]
        NAME_FIELD_NUMBER: _ClassVar[int]
        STRING_ARRAYS_FIELD_NUMBER: _ClassVar[int]
        STRING_ARRAY_FIELD_NUMBER: _ClassVar[int]
        UNIT_ID_FIELD_NUMBER: _ClassVar[int]
        UNKNOWN_ARRAYS_FIELD_NUMBER: _ClassVar[int]
        aggregate: AggregateEnum
        base_name: str
        boolean_array: BooleanArray
        boolean_arrays: DataMatrix.Column.BooleanArrays
        byte_array: ByteArray
        byte_arrays: DataMatrix.Column.ByteArrays
        bytestr_array: BytestrArray
        bytestr_arrays: DataMatrix.Column.BytestrArrays
        data_type: DataTypeEnum
        double_array: DoubleArray
        double_arrays: DataMatrix.Column.DoubleArrays
        float_array: FloatArray
        float_arrays: DataMatrix.Column.FloatArrays
        is_null: _containers.RepeatedScalarFieldContainer[bool]
        long_array: LongArray
        long_arrays: DataMatrix.Column.LongArrays
        longlong_array: LonglongArray
        longlong_arrays: DataMatrix.Column.LonglongArrays
        name: str
        string_array: StringArray
        string_arrays: DataMatrix.Column.StringArrays
        unit_id: int
        unknown_arrays: DataMatrix.Column.UnknownArrays
        def __init__(self, name: _Optional[str] = ..., base_name: _Optional[str] = ..., unit_id: _Optional[int] = ..., aggregate: _Optional[_Union[AggregateEnum, str]] = ..., data_type: _Optional[_Union[DataTypeEnum, str]] = ..., is_null: _Optional[_Iterable[bool]] = ..., string_array: _Optional[_Union[StringArray, _Mapping]] = ..., long_array: _Optional[_Union[LongArray, _Mapping]] = ..., float_array: _Optional[_Union[FloatArray, _Mapping]] = ..., boolean_array: _Optional[_Union[BooleanArray, _Mapping]] = ..., byte_array: _Optional[_Union[ByteArray, _Mapping]] = ..., double_array: _Optional[_Union[DoubleArray, _Mapping]] = ..., longlong_array: _Optional[_Union[LonglongArray, _Mapping]] = ..., bytestr_array: _Optional[_Union[BytestrArray, _Mapping]] = ..., string_arrays: _Optional[_Union[DataMatrix.Column.StringArrays, _Mapping]] = ..., long_arrays: _Optional[_Union[DataMatrix.Column.LongArrays, _Mapping]] = ..., float_arrays: _Optional[_Union[DataMatrix.Column.FloatArrays, _Mapping]] = ..., boolean_arrays: _Optional[_Union[DataMatrix.Column.BooleanArrays, _Mapping]] = ..., byte_arrays: _Optional[_Union[DataMatrix.Column.ByteArrays, _Mapping]] = ..., double_arrays: _Optional[_Union[DataMatrix.Column.DoubleArrays, _Mapping]] = ..., longlong_arrays: _Optional[_Union[DataMatrix.Column.LonglongArrays, _Mapping]] = ..., bytestr_arrays: _Optional[_Union[DataMatrix.Column.BytestrArrays, _Mapping]] = ..., unknown_arrays: _Optional[_Union[DataMatrix.Column.UnknownArrays, _Mapping]] = ...) -> None: ...
    AID_FIELD_NUMBER: _ClassVar[int]
    BASE_NAME_FIELD_NUMBER: _ClassVar[int]
    COLUMNS_FIELD_NUMBER: _ClassVar[int]
    NAME_FIELD_NUMBER: _ClassVar[int]
    ROW_START_FIELD_NUMBER: _ClassVar[int]
    VALUES_REMOVE_LENGTH_FIELD_NUMBER: _ClassVar[int]
    VALUES_START_FIELD_NUMBER: _ClassVar[int]
    VALUES_UPDATE_MODE_FIELD_NUMBER: _ClassVar[int]
    VU_APPEND: DataMatrix.UpdateModeEnum
    VU_INSERT: DataMatrix.UpdateModeEnum
    VU_REMOVE: DataMatrix.UpdateModeEnum
    VU_UPDATE: DataMatrix.UpdateModeEnum
    aid: int
    base_name: str
    columns: _containers.RepeatedCompositeFieldContainer[DataMatrix.Column]
    name: str
    row_start: int
    values_remove_length: int
    values_start: int
    values_update_mode: DataMatrix.UpdateModeEnum
    def __init__(self, name: _Optional[str] = ..., base_name: _Optional[str] = ..., aid: _Optional[int] = ..., columns: _Optional[_Iterable[_Union[DataMatrix.Column, _Mapping]]] = ..., row_start: _Optional[int] = ..., values_start: _Optional[int] = ..., values_update_mode: _Optional[_Union[DataMatrix.UpdateModeEnum, str]] = ..., values_remove_length: _Optional[int] = ...) -> None: ...

class DoubleArray(_message.Message):
    __slots__ = ["values"]
    VALUES_FIELD_NUMBER: _ClassVar[int]
    values: _containers.RepeatedScalarFieldContainer[float]
    def __init__(self, values: _Optional[_Iterable[float]] = ...) -> None: ...

class ErrorInfo(_message.Message):
    __slots__ = ["err_code", "minor_code", "reason"]
    class ErrorCodeEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = []
    AO_ACCESS_DENIED: ErrorInfo.ErrorCodeEnum
    AO_BAD_OPERATION: ErrorInfo.ErrorCodeEnum
    AO_BAD_PARAMETER: ErrorInfo.ErrorCodeEnum
    AO_CONNECTION_LOST: ErrorInfo.ErrorCodeEnum
    AO_CONNECT_FAILED: ErrorInfo.ErrorCodeEnum
    AO_CONNECT_REFUSED: ErrorInfo.ErrorCodeEnum
    AO_DUPLICATE_BASE_ATTRIBUTE: ErrorInfo.ErrorCodeEnum
    AO_DUPLICATE_NAME: ErrorInfo.ErrorCodeEnum
    AO_DUPLICATE_VALUE: ErrorInfo.ErrorCodeEnum
    AO_FILE_LOCKED: ErrorInfo.ErrorCodeEnum
    AO_HAS_BASE_ATTRIBUTE: ErrorInfo.ErrorCodeEnum
    AO_HAS_BASE_RELATION: ErrorInfo.ErrorCodeEnum
    AO_HAS_INSTANCES: ErrorInfo.ErrorCodeEnum
    AO_HAS_REFERENCES: ErrorInfo.ErrorCodeEnum
    AO_IMPLEMENTATION_PROBLEM: ErrorInfo.ErrorCodeEnum
    AO_INCOMPATIBLE_UNITS: ErrorInfo.ErrorCodeEnum
    AO_INVALID_ASAM_PATH: ErrorInfo.ErrorCodeEnum
    AO_INVALID_ATTRIBUTE_TYPE: ErrorInfo.ErrorCodeEnum
    AO_INVALID_BASETYPE: ErrorInfo.ErrorCodeEnum
    AO_INVALID_BASE_ELEMENT: ErrorInfo.ErrorCodeEnum
    AO_INVALID_BUILDUP_FUNCTION: ErrorInfo.ErrorCodeEnum
    AO_INVALID_COLUMN: ErrorInfo.ErrorCodeEnum
    AO_INVALID_COUNT: ErrorInfo.ErrorCodeEnum
    AO_INVALID_DATATYPE: ErrorInfo.ErrorCodeEnum
    AO_INVALID_ELEMENT: ErrorInfo.ErrorCodeEnum
    AO_INVALID_LENGTH: ErrorInfo.ErrorCodeEnum
    AO_INVALID_ORDINALNUMBER: ErrorInfo.ErrorCodeEnum
    AO_INVALID_RELATION: ErrorInfo.ErrorCodeEnum
    AO_INVALID_RELATIONSHIP: ErrorInfo.ErrorCodeEnum
    AO_INVALID_RELATION_RANGE: ErrorInfo.ErrorCodeEnum
    AO_INVALID_RELATION_TYPE: ErrorInfo.ErrorCodeEnum
    AO_INVALID_SET_TYPE: ErrorInfo.ErrorCodeEnum
    AO_INVALID_SMATLINK: ErrorInfo.ErrorCodeEnum
    AO_INVALID_SUBMATRIX: ErrorInfo.ErrorCodeEnum
    AO_INVALID_VALUEMATRIX_STRUCTURE: ErrorInfo.ErrorCodeEnum
    AO_IS_BASE_ATTRIBUTE: ErrorInfo.ErrorCodeEnum
    AO_IS_BASE_RELATION: ErrorInfo.ErrorCodeEnum
    AO_IS_MEASUREMENT_MATRIX: ErrorInfo.ErrorCodeEnum
    AO_MATH_ERROR: ErrorInfo.ErrorCodeEnum
    AO_MISSING_APPLICATION_ELEMENT: ErrorInfo.ErrorCodeEnum
    AO_MISSING_ATTRIBUTE: ErrorInfo.ErrorCodeEnum
    AO_MISSING_RELATION: ErrorInfo.ErrorCodeEnum
    AO_MISSING_VALUE: ErrorInfo.ErrorCodeEnum
    AO_NOT_FOUND: ErrorInfo.ErrorCodeEnum
    AO_NOT_IMPLEMENTED: ErrorInfo.ErrorCodeEnum
    AO_NOT_UNIQUE: ErrorInfo.ErrorCodeEnum
    AO_NO_MEMORY: ErrorInfo.ErrorCodeEnum
    AO_NO_PATH_TO_ELEMENT: ErrorInfo.ErrorCodeEnum
    AO_NO_SCALING_COLUMN: ErrorInfo.ErrorCodeEnum
    AO_OPEN_MODE_NOT_SUPPORTED: ErrorInfo.ErrorCodeEnum
    AO_QUERY_INCOMPLETE: ErrorInfo.ErrorCodeEnum
    AO_QUERY_INVALID: ErrorInfo.ErrorCodeEnum
    AO_QUERY_INVALID_RESULTTYPE: ErrorInfo.ErrorCodeEnum
    AO_QUERY_PROCESSING_ERROR: ErrorInfo.ErrorCodeEnum
    AO_QUERY_TIMEOUT_EXCEEDED: ErrorInfo.ErrorCodeEnum
    AO_QUERY_TYPE_INVALID: ErrorInfo.ErrorCodeEnum
    AO_SESSION_LIMIT_REACHED: ErrorInfo.ErrorCodeEnum
    AO_SESSION_NOT_ACTIVE: ErrorInfo.ErrorCodeEnum
    AO_SYSTEM_PROBLEM: ErrorInfo.ErrorCodeEnum
    AO_TRANSACTION_ALREADY_ACTIVE: ErrorInfo.ErrorCodeEnum
    AO_TRANSACTION_NOT_ACTIVE: ErrorInfo.ErrorCodeEnum
    AO_UNKNOWN_ERROR: ErrorInfo.ErrorCodeEnum
    AO_UNKNOWN_UNIT: ErrorInfo.ErrorCodeEnum
    ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    MINOR_CODE_FIELD_NUMBER: _ClassVar[int]
    REASON_FIELD_NUMBER: _ClassVar[int]
    err_code: ErrorInfo.ErrorCodeEnum
    minor_code: int
    reason: str
    def __init__(self, err_code: _Optional[_Union[ErrorInfo.ErrorCodeEnum, str]] = ..., minor_code: _Optional[int] = ..., reason: _Optional[str] = ...) -> None: ...

class FileControl(_message.Message):
    __slots__ = ["action", "aid", "iid", "url"]
    class ActionEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = []
    ACTION_FIELD_NUMBER: _ClassVar[int]
    AC_REMOVE: FileControl.ActionEnum
    AC_TAKE: FileControl.ActionEnum
    AID_FIELD_NUMBER: _ClassVar[int]
    IID_FIELD_NUMBER: _ClassVar[int]
    URL_FIELD_NUMBER: _ClassVar[int]
    action: FileControl.ActionEnum
    aid: int
    iid: int
    url: str
    def __init__(self, aid: _Optional[int] = ..., iid: _Optional[int] = ..., url: _Optional[str] = ..., action: _Optional[_Union[FileControl.ActionEnum, str]] = ...) -> None: ...

class FileIdentifier(_message.Message):
    __slots__ = ["aid", "attribute", "iid", "index"]
    AID_FIELD_NUMBER: _ClassVar[int]
    ATTRIBUTE_FIELD_NUMBER: _ClassVar[int]
    IID_FIELD_NUMBER: _ClassVar[int]
    INDEX_FIELD_NUMBER: _ClassVar[int]
    aid: int
    attribute: str
    iid: int
    index: int
    def __init__(self, aid: _Optional[int] = ..., iid: _Optional[int] = ..., attribute: _Optional[str] = ..., index: _Optional[int] = ...) -> None: ...

class FloatArray(_message.Message):
    __slots__ = ["values"]
    VALUES_FIELD_NUMBER: _ClassVar[int]
    values: _containers.RepeatedScalarFieldContainer[float]
    def __init__(self, values: _Optional[_Iterable[float]] = ...) -> None: ...

class Instance(_message.Message):
    __slots__ = ["aid", "iid"]
    AID_FIELD_NUMBER: _ClassVar[int]
    IID_FIELD_NUMBER: _ClassVar[int]
    aid: int
    iid: int
    def __init__(self, aid: _Optional[int] = ..., iid: _Optional[int] = ...) -> None: ...

class LongArray(_message.Message):
    __slots__ = ["values"]
    VALUES_FIELD_NUMBER: _ClassVar[int]
    values: _containers.RepeatedScalarFieldContainer[int]
    def __init__(self, values: _Optional[_Iterable[int]] = ...) -> None: ...

class LonglongArray(_message.Message):
    __slots__ = ["values"]
    VALUES_FIELD_NUMBER: _ClassVar[int]
    values: _containers.RepeatedScalarFieldContainer[int]
    def __init__(self, values: _Optional[_Iterable[int]] = ...) -> None: ...

class Model(_message.Message):
    __slots__ = ["entities", "enumerations"]
    class RelationTypeEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = []
    class RelationshipEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = []
    class Attribute(_message.Message):
        __slots__ = ["autogenerated", "base_name", "data_type", "enumeration", "id", "length", "name", "obligatory", "unique", "unit_id"]
        AUTOGENERATED_FIELD_NUMBER: _ClassVar[int]
        BASE_NAME_FIELD_NUMBER: _ClassVar[int]
        DATA_TYPE_FIELD_NUMBER: _ClassVar[int]
        ENUMERATION_FIELD_NUMBER: _ClassVar[int]
        ID_FIELD_NUMBER: _ClassVar[int]
        LENGTH_FIELD_NUMBER: _ClassVar[int]
        NAME_FIELD_NUMBER: _ClassVar[int]
        OBLIGATORY_FIELD_NUMBER: _ClassVar[int]
        UNIQUE_FIELD_NUMBER: _ClassVar[int]
        UNIT_ID_FIELD_NUMBER: _ClassVar[int]
        autogenerated: bool
        base_name: str
        data_type: DataTypeEnum
        enumeration: str
        id: int
        length: int
        name: str
        obligatory: bool
        unique: bool
        unit_id: int
        def __init__(self, name: _Optional[str] = ..., base_name: _Optional[str] = ..., data_type: _Optional[_Union[DataTypeEnum, str]] = ..., length: _Optional[int] = ..., obligatory: bool = ..., unique: bool = ..., autogenerated: bool = ..., unit_id: _Optional[int] = ..., enumeration: _Optional[str] = ..., id: _Optional[int] = ...) -> None: ...
    class EntitiesEntry(_message.Message):
        __slots__ = ["key", "value"]
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: Model.Entity
        def __init__(self, key: _Optional[str] = ..., value: _Optional[_Union[Model.Entity, _Mapping]] = ...) -> None: ...
    class Entity(_message.Message):
        __slots__ = ["aid", "attributes", "base_name", "name", "relations", "security_level"]
        class AttributesEntry(_message.Message):
            __slots__ = ["key", "value"]
            KEY_FIELD_NUMBER: _ClassVar[int]
            VALUE_FIELD_NUMBER: _ClassVar[int]
            key: str
            value: Model.Attribute
            def __init__(self, key: _Optional[str] = ..., value: _Optional[_Union[Model.Attribute, _Mapping]] = ...) -> None: ...
        class RelationsEntry(_message.Message):
            __slots__ = ["key", "value"]
            KEY_FIELD_NUMBER: _ClassVar[int]
            VALUE_FIELD_NUMBER: _ClassVar[int]
            key: str
            value: Model.Relation
            def __init__(self, key: _Optional[str] = ..., value: _Optional[_Union[Model.Relation, _Mapping]] = ...) -> None: ...
        AID_FIELD_NUMBER: _ClassVar[int]
        ATTRIBUTES_FIELD_NUMBER: _ClassVar[int]
        BASE_NAME_FIELD_NUMBER: _ClassVar[int]
        NAME_FIELD_NUMBER: _ClassVar[int]
        RELATIONS_FIELD_NUMBER: _ClassVar[int]
        SECURITY_LEVEL_FIELD_NUMBER: _ClassVar[int]
        aid: int
        attributes: _containers.MessageMap[str, Model.Attribute]
        base_name: str
        name: str
        relations: _containers.MessageMap[str, Model.Relation]
        security_level: int
        def __init__(self, name: _Optional[str] = ..., base_name: _Optional[str] = ..., aid: _Optional[int] = ..., security_level: _Optional[int] = ..., attributes: _Optional[_Mapping[str, Model.Attribute]] = ..., relations: _Optional[_Mapping[str, Model.Relation]] = ...) -> None: ...
    class Enumeration(_message.Message):
        __slots__ = ["items", "name"]
        class ItemsEntry(_message.Message):
            __slots__ = ["key", "value"]
            KEY_FIELD_NUMBER: _ClassVar[int]
            VALUE_FIELD_NUMBER: _ClassVar[int]
            key: str
            value: int
            def __init__(self, key: _Optional[str] = ..., value: _Optional[int] = ...) -> None: ...
        ITEMS_FIELD_NUMBER: _ClassVar[int]
        NAME_FIELD_NUMBER: _ClassVar[int]
        items: _containers.ScalarMap[str, int]
        name: str
        def __init__(self, name: _Optional[str] = ..., items: _Optional[_Mapping[str, int]] = ...) -> None: ...
    class EnumerationsEntry(_message.Message):
        __slots__ = ["key", "value"]
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: Model.Enumeration
        def __init__(self, key: _Optional[str] = ..., value: _Optional[_Union[Model.Enumeration, _Mapping]] = ...) -> None: ...
    class Relation(_message.Message):
        __slots__ = ["acl_reference", "base_name", "entity_aid", "entity_base_name", "entity_name", "inverse_base_name", "inverse_name", "inverse_range_max", "inverse_range_min", "name", "range_max", "range_min", "relation_type", "relationship", "virtual_reference"]
        ACL_REFERENCE_FIELD_NUMBER: _ClassVar[int]
        BASE_NAME_FIELD_NUMBER: _ClassVar[int]
        ENTITY_AID_FIELD_NUMBER: _ClassVar[int]
        ENTITY_BASE_NAME_FIELD_NUMBER: _ClassVar[int]
        ENTITY_NAME_FIELD_NUMBER: _ClassVar[int]
        INVERSE_BASE_NAME_FIELD_NUMBER: _ClassVar[int]
        INVERSE_NAME_FIELD_NUMBER: _ClassVar[int]
        INVERSE_RANGE_MAX_FIELD_NUMBER: _ClassVar[int]
        INVERSE_RANGE_MIN_FIELD_NUMBER: _ClassVar[int]
        NAME_FIELD_NUMBER: _ClassVar[int]
        RANGE_MAX_FIELD_NUMBER: _ClassVar[int]
        RANGE_MIN_FIELD_NUMBER: _ClassVar[int]
        RELATIONSHIP_FIELD_NUMBER: _ClassVar[int]
        RELATION_TYPE_FIELD_NUMBER: _ClassVar[int]
        VIRTUAL_REFERENCE_FIELD_NUMBER: _ClassVar[int]
        acl_reference: bool
        base_name: str
        entity_aid: int
        entity_base_name: str
        entity_name: str
        inverse_base_name: str
        inverse_name: str
        inverse_range_max: int
        inverse_range_min: int
        name: str
        range_max: int
        range_min: int
        relation_type: Model.RelationTypeEnum
        relationship: Model.RelationshipEnum
        virtual_reference: bool
        def __init__(self, name: _Optional[str] = ..., base_name: _Optional[str] = ..., inverse_name: _Optional[str] = ..., inverse_base_name: _Optional[str] = ..., entity_name: _Optional[str] = ..., entity_base_name: _Optional[str] = ..., entity_aid: _Optional[int] = ..., virtual_reference: bool = ..., acl_reference: bool = ..., range_min: _Optional[int] = ..., range_max: _Optional[int] = ..., inverse_range_min: _Optional[int] = ..., inverse_range_max: _Optional[int] = ..., relation_type: _Optional[_Union[Model.RelationTypeEnum, str]] = ..., relationship: _Optional[_Union[Model.RelationshipEnum, str]] = ...) -> None: ...
    ENTITIES_FIELD_NUMBER: _ClassVar[int]
    ENUMERATIONS_FIELD_NUMBER: _ClassVar[int]
    RS_ALL_REL: Model.RelationshipEnum
    RS_CHILD: Model.RelationshipEnum
    RS_FATHER: Model.RelationshipEnum
    RS_INFO_FROM: Model.RelationshipEnum
    RS_INFO_REL: Model.RelationshipEnum
    RS_INFO_TO: Model.RelationshipEnum
    RS_SUBTYPE: Model.RelationshipEnum
    RS_SUPERTYPE: Model.RelationshipEnum
    RT_FATHER_CHILD: Model.RelationTypeEnum
    RT_INFO: Model.RelationTypeEnum
    RT_INHERITANCE: Model.RelationTypeEnum
    entities: _containers.MessageMap[str, Model.Entity]
    enumerations: _containers.MessageMap[str, Model.Enumeration]
    def __init__(self, enumerations: _Optional[_Mapping[str, Model.Enumeration]] = ..., entities: _Optional[_Mapping[str, Model.Entity]] = ...) -> None: ...

class NtoMRelatedInstances(_message.Message):
    __slots__ = ["identifier", "related_iids"]
    IDENTIFIER_FIELD_NUMBER: _ClassVar[int]
    RELATED_IIDS_FIELD_NUMBER: _ClassVar[int]
    identifier: NtoMRelationIdentifier
    related_iids: _containers.RepeatedScalarFieldContainer[int]
    def __init__(self, identifier: _Optional[_Union[NtoMRelationIdentifier, _Mapping]] = ..., related_iids: _Optional[_Iterable[int]] = ...) -> None: ...

class NtoMRelationIdentifier(_message.Message):
    __slots__ = ["aid", "iid", "related_aid", "relation_name"]
    AID_FIELD_NUMBER: _ClassVar[int]
    IID_FIELD_NUMBER: _ClassVar[int]
    RELATED_AID_FIELD_NUMBER: _ClassVar[int]
    RELATION_NAME_FIELD_NUMBER: _ClassVar[int]
    aid: int
    iid: int
    related_aid: int
    relation_name: str
    def __init__(self, aid: _Optional[int] = ..., iid: _Optional[int] = ..., relation_name: _Optional[str] = ..., related_aid: _Optional[int] = ...) -> None: ...

class NtoMWriteRelatedInstances(_message.Message):
    __slots__ = ["change_mode", "relation_info"]
    class WriteTypeEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = []
    CHANGE_MODE_FIELD_NUMBER: _ClassVar[int]
    RELATION_INFO_FIELD_NUMBER: _ClassVar[int]
    WT_ADD: NtoMWriteRelatedInstances.WriteTypeEnum
    WT_REMOVE: NtoMWriteRelatedInstances.WriteTypeEnum
    WT_SET: NtoMWriteRelatedInstances.WriteTypeEnum
    change_mode: NtoMWriteRelatedInstances.WriteTypeEnum
    relation_info: NtoMRelatedInstances
    def __init__(self, change_mode: _Optional[_Union[NtoMWriteRelatedInstances.WriteTypeEnum, str]] = ..., relation_info: _Optional[_Union[NtoMRelatedInstances, _Mapping]] = ...) -> None: ...

class PasswordUpdate(_message.Message):
    __slots__ = ["new_password", "old_password", "user_id"]
    NEW_PASSWORD_FIELD_NUMBER: _ClassVar[int]
    OLD_PASSWORD_FIELD_NUMBER: _ClassVar[int]
    USER_ID_FIELD_NUMBER: _ClassVar[int]
    new_password: str
    old_password: str
    user_id: int
    def __init__(self, user_id: _Optional[int] = ..., old_password: _Optional[str] = ..., new_password: _Optional[str] = ...) -> None: ...

class SelectStatement(_message.Message):
    __slots__ = ["columns", "group_by", "joins", "order_by", "row_limit", "row_start", "values_limit", "values_start", "where"]
    class AttributeItem(_message.Message):
        __slots__ = ["aggregate", "aid", "attribute", "unit_id"]
        AGGREGATE_FIELD_NUMBER: _ClassVar[int]
        AID_FIELD_NUMBER: _ClassVar[int]
        ATTRIBUTE_FIELD_NUMBER: _ClassVar[int]
        UNIT_ID_FIELD_NUMBER: _ClassVar[int]
        aggregate: AggregateEnum
        aid: int
        attribute: str
        unit_id: int
        def __init__(self, aid: _Optional[int] = ..., attribute: _Optional[str] = ..., aggregate: _Optional[_Union[AggregateEnum, str]] = ..., unit_id: _Optional[int] = ...) -> None: ...
    class ConditionItem(_message.Message):
        __slots__ = ["condition", "conjunction"]
        class ConjuctionEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
            __slots__ = []
        class Condition(_message.Message):
            __slots__ = ["aid", "attribute", "boolean_array", "byte_array", "double_array", "float_array", "long_array", "longlong_array", "nested_statement", "operator", "string_array", "unit_id"]
            class OperatorEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
                __slots__ = []
            AID_FIELD_NUMBER: _ClassVar[int]
            ATTRIBUTE_FIELD_NUMBER: _ClassVar[int]
            BOOLEAN_ARRAY_FIELD_NUMBER: _ClassVar[int]
            BYTE_ARRAY_FIELD_NUMBER: _ClassVar[int]
            DOUBLE_ARRAY_FIELD_NUMBER: _ClassVar[int]
            FLOAT_ARRAY_FIELD_NUMBER: _ClassVar[int]
            LONGLONG_ARRAY_FIELD_NUMBER: _ClassVar[int]
            LONG_ARRAY_FIELD_NUMBER: _ClassVar[int]
            NESTED_STATEMENT_FIELD_NUMBER: _ClassVar[int]
            OPERATOR_FIELD_NUMBER: _ClassVar[int]
            OP_BETWEEN: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_CI_EQ: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_CI_GT: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_CI_GTE: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_CI_INSET: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_CI_LIKE: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_CI_LT: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_CI_LTE: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_CI_NEQ: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_CI_NOTINSET: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_CI_NOTLIKE: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_EQ: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_GT: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_GTE: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_INSET: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_IS_NOT_NULL: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_IS_NULL: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_LIKE: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_LT: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_LTE: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_NEQ: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_NOTINSET: SelectStatement.ConditionItem.Condition.OperatorEnum
            OP_NOTLIKE: SelectStatement.ConditionItem.Condition.OperatorEnum
            STRING_ARRAY_FIELD_NUMBER: _ClassVar[int]
            UNIT_ID_FIELD_NUMBER: _ClassVar[int]
            aid: int
            attribute: str
            boolean_array: BooleanArray
            byte_array: ByteArray
            double_array: DoubleArray
            float_array: FloatArray
            long_array: LongArray
            longlong_array: LonglongArray
            nested_statement: SelectStatement
            operator: SelectStatement.ConditionItem.Condition.OperatorEnum
            string_array: StringArray
            unit_id: int
            def __init__(self, aid: _Optional[int] = ..., attribute: _Optional[str] = ..., unit_id: _Optional[int] = ..., operator: _Optional[_Union[SelectStatement.ConditionItem.Condition.OperatorEnum, str]] = ..., string_array: _Optional[_Union[StringArray, _Mapping]] = ..., long_array: _Optional[_Union[LongArray, _Mapping]] = ..., float_array: _Optional[_Union[FloatArray, _Mapping]] = ..., boolean_array: _Optional[_Union[BooleanArray, _Mapping]] = ..., byte_array: _Optional[_Union[ByteArray, _Mapping]] = ..., double_array: _Optional[_Union[DoubleArray, _Mapping]] = ..., longlong_array: _Optional[_Union[LonglongArray, _Mapping]] = ..., nested_statement: _Optional[_Union[SelectStatement, _Mapping]] = ...) -> None: ...
        CONDITION_FIELD_NUMBER: _ClassVar[int]
        CONJUNCTION_FIELD_NUMBER: _ClassVar[int]
        CO_AND: SelectStatement.ConditionItem.ConjuctionEnum
        CO_CLOSE: SelectStatement.ConditionItem.ConjuctionEnum
        CO_NOT: SelectStatement.ConditionItem.ConjuctionEnum
        CO_OPEN: SelectStatement.ConditionItem.ConjuctionEnum
        CO_OR: SelectStatement.ConditionItem.ConjuctionEnum
        condition: SelectStatement.ConditionItem.Condition
        conjunction: SelectStatement.ConditionItem.ConjuctionEnum
        def __init__(self, conjunction: _Optional[_Union[SelectStatement.ConditionItem.ConjuctionEnum, str]] = ..., condition: _Optional[_Union[SelectStatement.ConditionItem.Condition, _Mapping]] = ...) -> None: ...
    class GroupByItem(_message.Message):
        __slots__ = ["aid", "attribute"]
        AID_FIELD_NUMBER: _ClassVar[int]
        ATTRIBUTE_FIELD_NUMBER: _ClassVar[int]
        aid: int
        attribute: str
        def __init__(self, aid: _Optional[int] = ..., attribute: _Optional[str] = ...) -> None: ...
    class JoinItem(_message.Message):
        __slots__ = ["aid_from", "aid_to", "join_type", "relation"]
        class JoinTypeEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
            __slots__ = []
        AID_FROM_FIELD_NUMBER: _ClassVar[int]
        AID_TO_FIELD_NUMBER: _ClassVar[int]
        JOIN_TYPE_FIELD_NUMBER: _ClassVar[int]
        JT_DEFAULT: SelectStatement.JoinItem.JoinTypeEnum
        JT_OUTER: SelectStatement.JoinItem.JoinTypeEnum
        RELATION_FIELD_NUMBER: _ClassVar[int]
        aid_from: int
        aid_to: int
        join_type: SelectStatement.JoinItem.JoinTypeEnum
        relation: str
        def __init__(self, aid_from: _Optional[int] = ..., aid_to: _Optional[int] = ..., relation: _Optional[str] = ..., join_type: _Optional[_Union[SelectStatement.JoinItem.JoinTypeEnum, str]] = ...) -> None: ...
    class OrderByItem(_message.Message):
        __slots__ = ["aid", "attribute", "order"]
        class OrderEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
            __slots__ = []
        AID_FIELD_NUMBER: _ClassVar[int]
        ATTRIBUTE_FIELD_NUMBER: _ClassVar[int]
        OD_ASCENDING: SelectStatement.OrderByItem.OrderEnum
        OD_DESCENDING: SelectStatement.OrderByItem.OrderEnum
        ORDER_FIELD_NUMBER: _ClassVar[int]
        aid: int
        attribute: str
        order: SelectStatement.OrderByItem.OrderEnum
        def __init__(self, aid: _Optional[int] = ..., attribute: _Optional[str] = ..., order: _Optional[_Union[SelectStatement.OrderByItem.OrderEnum, str]] = ...) -> None: ...
    COLUMNS_FIELD_NUMBER: _ClassVar[int]
    GROUP_BY_FIELD_NUMBER: _ClassVar[int]
    JOINS_FIELD_NUMBER: _ClassVar[int]
    ORDER_BY_FIELD_NUMBER: _ClassVar[int]
    ROW_LIMIT_FIELD_NUMBER: _ClassVar[int]
    ROW_START_FIELD_NUMBER: _ClassVar[int]
    VALUES_LIMIT_FIELD_NUMBER: _ClassVar[int]
    VALUES_START_FIELD_NUMBER: _ClassVar[int]
    WHERE_FIELD_NUMBER: _ClassVar[int]
    columns: _containers.RepeatedCompositeFieldContainer[SelectStatement.AttributeItem]
    group_by: _containers.RepeatedCompositeFieldContainer[SelectStatement.GroupByItem]
    joins: _containers.RepeatedCompositeFieldContainer[SelectStatement.JoinItem]
    order_by: _containers.RepeatedCompositeFieldContainer[SelectStatement.OrderByItem]
    row_limit: int
    row_start: int
    values_limit: int
    values_start: int
    where: _containers.RepeatedCompositeFieldContainer[SelectStatement.ConditionItem]
    def __init__(self, columns: _Optional[_Iterable[_Union[SelectStatement.AttributeItem, _Mapping]]] = ..., where: _Optional[_Iterable[_Union[SelectStatement.ConditionItem, _Mapping]]] = ..., joins: _Optional[_Iterable[_Union[SelectStatement.JoinItem, _Mapping]]] = ..., order_by: _Optional[_Iterable[_Union[SelectStatement.OrderByItem, _Mapping]]] = ..., group_by: _Optional[_Iterable[_Union[SelectStatement.GroupByItem, _Mapping]]] = ..., row_limit: _Optional[int] = ..., row_start: _Optional[int] = ..., values_limit: _Optional[int] = ..., values_start: _Optional[int] = ...) -> None: ...

class StringArray(_message.Message):
    __slots__ = ["values"]
    VALUES_FIELD_NUMBER: _ClassVar[int]
    values: _containers.RepeatedScalarFieldContainer[str]
    def __init__(self, values: _Optional[_Iterable[str]] = ...) -> None: ...

class ValueMatrixRequestStruct(_message.Message):
    __slots__ = ["aid", "attributes", "columns", "exd_group_ids", "iid", "mode", "values_limit", "values_start"]
    class ModeEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = []
    class ColumnItem(_message.Message):
        __slots__ = ["name", "unit_id"]
        NAME_FIELD_NUMBER: _ClassVar[int]
        UNIT_ID_FIELD_NUMBER: _ClassVar[int]
        name: str
        unit_id: int
        def __init__(self, name: _Optional[str] = ..., unit_id: _Optional[int] = ...) -> None: ...
    AID_FIELD_NUMBER: _ClassVar[int]
    ATTRIBUTES_FIELD_NUMBER: _ClassVar[int]
    COLUMNS_FIELD_NUMBER: _ClassVar[int]
    EXD_GROUP_IDS_FIELD_NUMBER: _ClassVar[int]
    IID_FIELD_NUMBER: _ClassVar[int]
    MODE_FIELD_NUMBER: _ClassVar[int]
    MO_CALCULATED: ValueMatrixRequestStruct.ModeEnum
    MO_EXD_VIRTUAL_DATA: ValueMatrixRequestStruct.ModeEnum
    MO_STORAGE: ValueMatrixRequestStruct.ModeEnum
    VALUES_LIMIT_FIELD_NUMBER: _ClassVar[int]
    VALUES_START_FIELD_NUMBER: _ClassVar[int]
    aid: int
    attributes: _containers.RepeatedScalarFieldContainer[str]
    columns: _containers.RepeatedCompositeFieldContainer[ValueMatrixRequestStruct.ColumnItem]
    exd_group_ids: _containers.RepeatedScalarFieldContainer[int]
    iid: int
    mode: ValueMatrixRequestStruct.ModeEnum
    values_limit: int
    values_start: int
    def __init__(self, mode: _Optional[_Union[ValueMatrixRequestStruct.ModeEnum, str]] = ..., aid: _Optional[int] = ..., iid: _Optional[int] = ..., attributes: _Optional[_Iterable[str]] = ..., columns: _Optional[_Iterable[_Union[ValueMatrixRequestStruct.ColumnItem, _Mapping]]] = ..., values_limit: _Optional[int] = ..., values_start: _Optional[int] = ..., exd_group_ids: _Optional[_Iterable[int]] = ...) -> None: ...

class DataTypeEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = []

class AggregateEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = []
